using System;
using System.Collections.Generic;
using System.Text;

namespace Project13
{
    internal class Patient : IRecoverable //use crtl+. to implement the interface,
                                          //it will generate a stub for the Recover method,
                                          //which we can then fill in with our own implementation.
                                          //
                                          //what is stub?
                                          //a stub is a piece of code that is generated by the IDE to provide a placeholder
                                          //for a method or property that has not yet been implemented, it allows you to
                                          //compile and run your code without having to provide an implementation for the
                                          //method or property, it is often used when you are still working on the
                                          //implementation of the method or property, and you want to be able to test
                                          //other parts of your code without having to worry about the implementation
                                          //of the method or property.
    {
        public string Recover()
        {
            return "Patient is recovering, they are taking their medication and getting plenty of rest.";
            throw new NotImplementedException();
        }
    }
}
